### ISSUE TITLE
Multithreaded forking and environment access locks

### ISSUE THREAD

**Issue by fedya** [OpenMandrivaAssociation/builder-c#1]
ABF builders stucks after time (12-24Hours)
WHY:
https://rachelbythebay.com/w/2014/08/16/forkenv/

> It's trying to get a lock in glibc within unsetenv(). This never succeeds, since we're in the child and no thread exists on this side of things to release that lock. We copied the lock in the "set" state, and there it will stay forever.

builder process locked here "__lll_lock_wait_private" 

explanation:

> If you see your process blocked in "__lll_lock_wait_private" with unsetenv or setenv listed earlier in the stack, you've probably done this, and it just decided now was the right time to pop up and make trouble for you.

**Comment by fedya** [comment]
Process locked here "__lll_lock_wait_private" 

explanation:

> If you see your process blocked in "__lll_lock_wait_private" with unsetenv or setenv listed earlier in the stack, you've probably done this, and it just decided now was the right time to pop up and make trouble for you.

**Comment by tpgxyz** [comment]
@fedya  Have you tried to run clang analyzer on builder-c ?

I may suggest this may be "double free" issue.

**Comment by fedya** [comment]
we analyzed it via gdb

**Comment by DuratarskeyK** [comment]
The double free should just crash the app, If i'm correct.

**Comment by tpgxyz** [comment]
@fedya  @DuratarskeyK  have you tried to run
strace -p builder-c_PID
pstack builder-c_PID

**Comment by fedya** [comment]
weird but i rebuilt builder image based on cooker
and looks like builders works more than 2 weeks without stuck
